exclude: ^(.idea|.vscode/)

repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-toml
      - id: check-yaml
        args: [--allow-multiple-documents]
        exclude: ^deploy/|^galaxy/cli/cookiecutter
      - id: detect-private-key
      - id: pretty-format-json
        args:
          - "--autofix"
          - "--indent=2"
          - "--no-sort-keys"

  - repo: local
    hooks:
      - id: update-lockfile
        name: update lockfile
        entry: make lock
        language: system
        always_run: true
        pass_filenames: false

  - repo: https://github.com/norwoodj/helm-docs
    rev:  "v1.14.2"
    hooks:
      - id: helm-docs-built
        args:
          # Make the tool search for charts only under the `deploy/helm` directory
          - --chart-search-root=deploy/helm
