rely:
  token: "{{ env('RELY_API_TOKEN') }}"
  url: "{{ env('RELY_API_URL') }}"

integration:
  id: "{{ env('RELY_INTEGRATION_ID') }}"
  type: "sonarqube"
  executionType: "{{ env('RELY_INTEGRATION_EXECUTION_TYPE') | default('cronjob', true) }}"

  # The configuration for the integration.
  scheduledInterval: "{{ env('RELY_INTEGRATION_DAEMON_INTERVAL') | default(60, true) | int  }}"
  defaultModelMappings:
    sonarqube.v1.project: "service"
    sonarqube.v1.issue: "cve"
  properties:
    apiToken: "{{ env('RELY_INTEGRATION_SONARQUBE_TOKEN') | default('', true) }}"
    serverUrl: "{{ env('RELY_INTEGRATION_SONARQUBE_URL') | default('', true) }}"
