apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  config.yaml: |
    rely:
      token: {{ .Values.config.rely.token }}
      url: {{ .Values.config.rely.url }}
    integration:
      id: {{ .Values.config.integration.id }}
      type: {{ .Values.config.integration.type }}
      executionType: {{ .Values.config.integration.executionType }}
      scheduledInterval: {{ .Values.config.integration.scheduledInterval }}
      properties:
{{ toYaml .Values.config.integration.properties | indent 8 }}
