# templates/cronjob.yaml
{{ $release_name := .Release.Name -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $release_name }}-cronjob
spec:
  schedule: "{{ .Values.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cronjob
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            env:
            {{- range .Values.env }}
            {{- if .secret }}
              - name: {{ .name }}
                valueFrom:
                  secretKeyRef:
                    name: {{ $release_name }}-secret
                    key: {{ .name }}
            {{- else }}
              - name: {{ .name }}
                value: {{ .value | quote }}
            {{- end }}
            {{- end }}
            volumeMounts:
            - name: config-volume
              mountPath: /config
          volumes:
          - name: config-volume
            configMap:
              name: {{ $release_name }}-config
          restartPolicy: OnFailure
