{{- if eq .Values.integration.type "flux" }}
{{- range .Values.flux.namespaces }}
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: {{ include "galaxy-helm.fullname" $ }}
  namespace: {{ . }}
spec:
  type: generic
  address: http://{{ include "galaxy-helm.fullname" $ }}.{{ $.Release.Namespace }}.svc.cluster.local/flux/webhook
{{- end }}
{{- end }}
