# {{ include "galaxy-helm.required.envs" . | substr 0 0}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "galaxy-helm.fullname" . }}
  labels:
    {{- include "galaxy-helm.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.env }}
  {{ $key }}: {{ $val | toString | b64enc }}
  {{- end}}
