{{- if .Values.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "galaxy-helm.serviceAccountName" . }}
  labels:
    {{- include "galaxy-helm.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  {{- with .Values.clusterRole.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "galaxy-helm.labels" . | nindent 4 }}
  name: {{ include "galaxy-helm.clusterRoleName" . }}
rules:
  - apiGroups:
      {{- range .Values.clusterRole.apiGroups  }}
      - {{ . }}
      {{- end }}
    resources:
      {{- range .Values.clusterRole.resources }}
      - {{ . }}
      {{- end }}
    verbs:
      - "get"
      - "watch"
      - "list"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  {{- with .Values.clusterRoleBinding.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "galaxy-helm.labels" . | nindent 4 }}
  name: {{ include "galaxy-helm.clusterRoleBindingName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "galaxy-helm.clusterRoleName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "galaxy-helm.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
