rely:
  token: "{{ "{{" }} env('RELY_API_TOKEN') {{ "}}" }}"
  url: "{{ "{{" }} env('RELY_API_URL') | default('https://magneto-api-dev.rely.io', true) {{ "}}" }}"
integration:
  # The identifier of this integration instance.
  id: "{{ "{{" }} env('RELY_INTEGRATION_ID') | default('00000', true) {{ "}}" }}"
  # The type of the integration.
  type: "{{ cookiecutter.integration_name }}"
# The execution type of the integration.
  executionType: "{{ "{{" }} env('RELY_INTEGRATION_EXECUTION_TYPE') | default('cronjob', true) {{ "}}" }}"
  # The configuration for the integration.
  scheduledInterval: 60
  defaultModelMappings: {}
  properties:
    foo: "bar"
