rely:
  token: "{{ "{{" }} env('RELY_API_TOKEN') {{ "}}" }}"
  url: "{{ "{{" }} env('RELY_API_URL') {{ "}}" }}"
integration:
  id: "{{ "{{" }} env('RELY_INTEGRATION_ID') {{ "}}" }}"
  type: "{{ cookiecutter.integration_name }}"
  executionType: "{{ "{{" }} env('RELY_INTEGRATION_EXECUTION_TYPE') | default('cronjob', true) {{ "}}" }}"

  scheduledInterval: "{{ "{{" }}  env('RELY_INTEGRATION_DAEMON_INTERVAL') | default(60, true) | int {{ "}}" }}"
  defaultModelMappings: {}
  properties:
    foo: "bar"
