# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build and Test Galaxy

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
    env:
      VENV_PATH: "${{ github.path }}/.venv"
      POETRY_HOME: "${{ github.path }}/.cache/.poetry"
      BIN_PATH: "${{github.path}}/.cache/.bin"



    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup environment
      run: |
        mkdir -p ${VENV_PATH} ${POETRY_HOME} ${BIN_PATH}
        export PYTHONUNBUFFERED=1
        export PYTHONDONTWRITEBYTECODE=1
        export POETRY_VIRTUALENVS_IN_PROJECT=true
        apt-get update && apt-get install --no-install-recommends -y build-essential curl git
        cp /usr/bin/make ${BIN_PATH}
        make install
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

